remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Causal Inference & Machine Learning for Online Controlled Experiments in Industry"
description: "A Hands-on Tutorial at ECML / PKDD 2024 workshop"
